# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HA-Qdevice add-on
version: "0.0.2"
slug: qdevice
description: Home assistant Qdevice addon to give a third voter for PVE Cluster
url: "https://github.com/Nerexbcd/HA-Qdevice/tree/master/HA-Qdevice"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - addon_config:rw

ports:
  2222/tcp: 22
  5404/udp: 5404
  5405/udp: 5405
  5406/udp: 5406

options:
  root_password: null

schema:
  root_password: password?