# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HA-Qdevice add-on
version: "0.0.7"
slug: qdevice
description: Home assistant Qdevice addon to give a third voter for PVE Cluster
url: "https://github.com/Nerexbcd/HA-Qdevice/tree/master/HA-Qdevice"
arch:
  - armhf
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: False
    path: "/etc/corosync"
    
ports:
  22/tcp: 2222
  5404/udp: 5404
  5405/udp: 5405
  5406/udp: 5406

options:
  root_password: null

schema:
  root_password: password?